from __future__ import annotations

from typing import Any


class MockProvider:
    """Deterministic provider for runtime tests and fork-ready demos."""

    def generate_json(
        self,
        *,
        system_prompt: str,
        user_payload: dict[str, Any],
        schema: dict[str, Any],
        model: str = "mock",
        temperature: float = 0,
        max_output_tokens: int | None = None,
    ) -> dict[str, Any]:
        task = user_payload.get("task")
        if task == "structure_analysis":
            return mock_structure_analysis(user_payload)
        if task == "workflow_analysis":
            return mock_workflow_analysis(user_payload)
        if task == "patterns":
            return mock_patterns(user_payload)
        if task == "review_report":
            return mock_review_report(user_payload)
        return {"schema_version": 1}


def mock_structure_analysis(payload: dict[str, Any]) -> dict[str, Any]:
    package = payload["skill_package"]
    return {
        "schema_version": 1,
        "skill_id": package["id"],
        "source": {
            "repo": payload.get("source", {}).get("url"),
            "commit": payload.get("source", {}).get("resolved_commit"),
            "root_path": package["root_path"],
            "skill_md_path": package["skill_md_path"],
        },
        "frontmatter": {},
        "summary": {
            "zh": f"{package['name']} 的结构分析占位结果。",
            "en": f"Placeholder structure analysis for {package['name']}.",
        },
        "target_agents": ["unknown"],
        "skill_type": {"primary": "unknown", "secondary": []},
        "identity": {
            "one_line": {
                "zh": f"{package['name']} 是一个待真实模型确认的 skill 包。",
                "en": f"{package['name']} is a skill package awaiting real model analysis.",
            },
            "skill_type": {"primary": "unknown", "secondary": []},
            "target_agents": ["unknown"],
            "primary_outputs": [],
            "value_proposition": {"zh": "用于演示拆解链路。", "en": "Used to demonstrate the anatomy pipeline."},
            "confidence": {"overall": "unknown", "notes": "Generated by MockProvider."},
            "evidence": [],
        },
        "trigger_conditions": {"explicit": [], "inferred": []},
        "activation": {
            "explicit_triggers": [],
            "semantic_triggers": [],
            "negative_triggers": [],
            "boundary_conditions": ["Requires a SKILL.md-style package."],
            "misfire_risks": ["Mock analysis is not evidence-grounded."],
            "evidence": [],
        },
        "inputs": [],
        "outputs": [],
        "file_anatomy": {
            "skill_md": {
                "purpose": "Primary skill instruction file.",
                "sections": [],
            },
            "scripts": package.get("scripts", []),
            "references": package.get("references", []),
            "assets": package.get("assets", []),
        },
        "resource_roles": [
            {
                "path": package.get("skill_md_path", "SKILL.md"),
                "role": "Primary instruction and trigger surface.",
                "stage": "inspect",
                "read_policy": "must_read",
                "reuse_value": "medium",
                "risk": "Mock role, requires real model confirmation.",
                "evidence": [],
            }
        ],
        "context_strategy": {
            "summary": "Unknown until a real analyst model inspects the skill text.",
            "progressive_disclosure": "unknown",
            "evidence": [],
        },
        "tools": [],
        "risks": [],
        "confidence": {"overall": "unknown", "notes": "Generated by MockProvider."},
    }


def mock_workflow_analysis(payload: dict[str, Any]) -> dict[str, Any]:
    skill_id = payload["structure_analysis"]["skill_id"]
    return {
        "schema_version": 1,
        "skill_id": skill_id,
        "workflow_summary": {
            "zh": "占位工作流：识别技能、读取结构、产出分析。",
            "en": "Placeholder workflow: detect skill, inspect structure, produce analysis.",
        },
        "workflow_steps": [
            {
                "id": "step_1",
                "name": {"zh": "识别技能包", "en": "Detect skill package"},
                "action": {"zh": "根据 SKILL.md 定位技能包。", "en": "Locate the package through SKILL.md."},
                "step_type": "detect",
                "actor": "model",
                "evidence": [],
                "inferred": True,
                "confidence": "low",
            },
            {
                "id": "step_2",
                "name": {"zh": "交付分析", "en": "Deliver analysis"},
                "action": {"zh": "输出结构化分析 artifact。", "en": "Emit structured analysis artifacts."},
                "step_type": "deliver",
                "actor": "model",
                "evidence": [],
                "inferred": True,
                "confidence": "low",
            },
        ],
        "decision_points": [],
        "verification_points": [],
        "failure_modes": [],
        "context_loading": {"strategy": "unknown", "details": "Mock output", "evidence": []},
        "tool_boundary": {
            "model_responsibilities": [],
            "script_responsibilities": [],
            "external_tool_responsibilities": [],
            "evidence": [],
        },
        "mermaid": {"flowchart": "flowchart TD\n  A[Detect Skill] --> B[Analyze Structure]\n  B --> C[Deliver Artifacts]"},
        "reusable_candidates": [],
        "warnings": ["Mock workflow analysis is not evidence-grounded."],
        "workflow_trace": {
            "summary": {"zh": "从识别 skill 包到交付结构化 artifact。", "en": "From detecting the skill package to delivering structured artifacts."},
            "pipeline": ["detect", "inspect", "deliver"],
            "steps": [
                {
                    "id": "trace_1",
                    "name": {"zh": "识别技能包", "en": "Detect skill package"},
                    "input": "inventory.skill_packages",
                    "action": "Locate SKILL.md and package metadata.",
                    "output": "skill package candidate",
                    "actor": "model",
                    "resources": ["SKILL.md"],
                    "downstream": ["trace_2"],
                    "confidence": "low",
                    "inferred": True,
                    "evidence": [],
                }
            ],
            "decision_points": [],
            "verification_points": [],
            "failure_modes": ["Mock trace has no source evidence."],
        },
    }


def mock_patterns(payload: dict[str, Any]) -> dict[str, Any]:
    examples = [{"skill_id": item["skill_id"], "source_path": item.get("source_path"), "evidence": []} for item in payload.get("skills", [])]
    return {
        "schema_version": 1,
        "patterns": [
            {
                "id": "skill-package-anatomy",
                "canonical_name": "Skill Package Anatomy",
                "zh_name": "技能包解剖",
                "category": "packaging",
                "status": "candidate" if len(examples) < 2 else "emerging",
                "definition": {"zh": "围绕 SKILL.md 识别技能包结构。", "en": "Identify package structure around SKILL.md."},
                "problem": {"zh": "技能资产分散在多个文件中。", "en": "Skill assets are spread across files."},
                "solution": {"zh": "用统一 inventory 归档结构。", "en": "Use a unified inventory to capture structure."},
                "when_to_use": {"zh": "分析 SKILL.md 风格仓库时使用。", "en": "Use when analyzing SKILL.md-style repositories."},
                "signals": [],
                "examples": examples,
                "counterexamples": [],
                "reusable_template": {"zh": "先收集，再分析，再渲染。", "en": "Collect, analyze, then render."},
                "related_patterns": [],
                "minimum_examples_required": 2,
                "confidence": "low",
            }
        ],
        "reuse_assets": {
            "patterns": ["skill-package-anatomy"],
            "templates": [],
            "checklists": ["Collect files", "Analyze structure", "Trace workflow", "Render learning assets"],
            "anti_patterns": ["Treating file lists as explanations"],
            "extension_ideas": ["Compare the same skill across multiple LLMs"],
        },
    }


def mock_review_report(payload: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "skill_id": payload.get("skill_id"),
        "status": "needs_revision",
        "scores": {
            "evidence_score": 1,
            "structure_score": 2,
            "workflow_score": 2,
            "pattern_score": 1,
            "bilingual_score": 3,
            "obsidian_score": 3,
        },
        "issues": [
            {
                "severity": "major",
                "category": "evidence",
                "description": {"zh": "Mock 输出缺少真实证据。", "en": "Mock output lacks real evidence."},
            }
        ],
        "unsupported_claims": [],
        "missing_evidence": [],
        "over_inference": [],
        "approved_for_publish": {"value": False, "rationale": "Mock artifacts require real analyst review."},
        "evidence_audit": {
            "supported_claims": [],
            "inferred_claims": ["Mock structure and workflow are placeholders."],
            "unsupported_claims": [],
            "missing_evidence": ["Real source quotes are not available in mock output."],
            "conflicts": [],
            "publishable": "needs_revision",
            "rationale": "Mock artifacts demonstrate shape only and require real evidence-grounded analysis.",
        },
    }
